# Generated by Django 4.0.10 on 2024-02-05 05:35

from django.db import migrations, models
import services.domain.customers.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('external_id', models.CharField(max_length=60, unique=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE')], default=services.domain.customers.constants.CustomerStatus['ACTIVE'])),
                ('score', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preapproved_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
